# Generated by Django 6.0.4 on 2026-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("S", "Safety"),
                            ("M", "Medical"),
                            ("E", "Educational"),
                            ("O", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("occurred_on", models.DateField()),
                ("occured_at", models.TimeField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("M", "Mild"),
                            ("MD", "Moderate"),
                            ("S", "Severe"),
                            ("LT", "Life-Threatening"),
                            ("F", "Fatal"),
                        ],
                        max_length=4,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="children.child"
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staffing.staffprofile",
                    ),
                ),
            ],
        ),
    ]
