# Generated by Django 6.0.4 on 2026-06-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleassignment",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="accounts.role"
            ),
        ),
    ]
