# Generated by Django 6.0.4 on 2026-06-17 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roleassignment",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="facilities.room",
            ),
        ),
        migrations.AddField(
            model_name="roleassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
