# Generated by Django 6.0.4 on 2026-06-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_clerical",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_director",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_instructor",
            field=models.BooleanField(default=False),
        ),
    ]
