# Generated by Django 6.0.4 on 2026-06-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("F", "Final"),
                            ("M", "Final - Modified"),
                        ],
                        default="D",
                        max_length=3,
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CheckInOutEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CI-AM", "Check-In(AM)"),
                            ("CO-AM", "Check-Out(AM)"),
                            ("CI-PM", "Pickup(PM)"),
                            ("CO-PM", "Check-Out(PM)"),
                        ],
                        max_length=5,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
