# Generated by Django 6.0.4 on 2026-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Draft"),
                            ("F", "Final"),
                            ("M", "Final - Modified"),
                        ],
                        default="D",
                        max_length=3,
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="children.child"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckInOutEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CI-AM", "Check-In(AM)"),
                            ("CO-AM", "Check-Out(AM)"),
                            ("CI-PM", "Pickup(PM)"),
                            ("CO-PM", "Check-Out(PM)"),
                        ],
                        max_length=5,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="children.child"
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="children.authorizedpickupprofile",
                    ),
                ),
            ],
        ),
    ]
