# Generated by Django 6.0.4 on 2026-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinoutevent",
            name="recorded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staffing.staffprofile"
            ),
        ),
    ]
