# Generated by Django 6.0.4 on 2026-06-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="children.child"
            ),
        ),
        migrations.AddField(
            model_name="checkinoutevent",
            name="attendance_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_in_out_events",
                to="attendance.attendancerecord",
            ),
        ),
        migrations.AddField(
            model_name="checkinoutevent",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="children.authorizedpickupprofile",
            ),
        ),
    ]
