# Generated by Django 6.0.4 on 2026-05-18 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
        ("children", "0002_remove_custodyrestriction_restriction_type_and_more"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkinoutevent",
            name="performed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="children.authorizedpickupprofile",
            ),
        ),
        migrations.AlterField(
            model_name="checkinoutevent",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staffing.staffprofile",
            ),
        ),
    ]
