# Generated by Django 6.0.4 on 2026-06-17 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0002_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinoutevent",
            name="recorded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staffing.staffprofile",
            ),
        ),
        migrations.AddConstraint(
            model_name="attendancerecord",
            constraint=models.UniqueConstraint(
                fields=("child", "date"), name="one_attendance_record_per_child_per_day"
            ),
        ),
    ]
