# Generated by Django 6.0.4 on 2026-06-15 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_checkinoutevent_performed_by_and_more'),
        ('children', '0004_child_programs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='checkinoutevent',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='checkinoutevent',
            name='child',
        ),
        migrations.AddField(
            model_name='checkinoutevent',
            name='attendance_record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='check_in_out_events', to='attendance.attendancerecord'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('child', 'date'), name='one_attendance_record_per_child_per_day'),
        ),
    ]
