# Generated by Django 6.0.4 on 2026-06-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("G", "General"),
                    ("F", "Financial"),
                    ("L", "Legal"),
                    ("I", "Internal"),
                    ("O", "Other"),
                    ("M", "Medical"),
                ],
                max_length=12,
            ),
        ),
    ]
