# Generated by Django 6.0.4 on 2026-06-17 13:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("a0a07645-8cfe-42a9-bd0b-ca6024081f2e"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
