# Generated by Django 6.0.4 on 2026-06-17 15:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_alter_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
