# Generated by Django 6.0.4 on 2026-06-17 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0002_initial"),
        ("enrollment", "0001_initial"),
        ("facilities", "0001_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childschedule",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="staffing.staffprofile",
            ),
        ),
        migrations.AddField(
            model_name="childschedule",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facilities.program"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="facilities.program",
            ),
        ),
        migrations.AddField(
            model_name="childschedule",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enrollment.enrollment"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "A")),
                fields=("child",),
                name="one_active_enrollment_per_child",
            ),
        ),
    ]
