# Generated by Django 6.0.4 on 2026-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
        ("enrollment", "0001_initial"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="childschedule",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facilities.program"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="children.child"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facilities.program"
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facilities.site"
            ),
        ),
        migrations.AddField(
            model_name="childschedule",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="enrollment.enrollment"
            ),
        ),
    ]
