# Generated by Django 6.0.4 on 2026-05-18 04:54

import applications.enrollment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="childschedule",
            name="days_of_week",
            field=models.JSONField(
                default=applications.enrollment.models.days_of_week_template
            ),
        ),
    ]
