# Generated by Django 6.0.4 on 2026-06-14 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0004_child_programs"),
        ("enrollment", "0003_alter_childschedule_days_of_week"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="site",
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="children.child",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="facilities.program",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "A")),
                fields=("child",),
                name="one_active_enrollment_per_child",
            ),
        ),
    ]
