# Generated by Django 6.0.4 on 2026-06-17 13:40

import django.db.models.deletion
import encrypted_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allergen", models.CharField(max_length=50)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("M", "Mild"),
                            ("MD", "Moderate"),
                            ("S", "Severe"),
                            ("LT", "Life-Threatening"),
                            ("F", "Fatal"),
                        ],
                        max_length=2,
                    ),
                ),
                ("instructions", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=325)),
                ("last_name", models.CharField(max_length=325)),
                ("date_of_birth", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("E", "Enrolled"),
                            ("A", "Active"),
                            ("C", "Cancelled"),
                            ("S", "Suspended"),
                            ("X", "Transferred"),
                        ],
                        max_length=3,
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ChildGuardianRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("P", "Parent"),
                            ("GP", "Grandparent"),
                            ("AV", "Aunt/Uncle"),
                            ("S", "Sibling"),
                            ("G", "Legal Guardian"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_primary", models.BooleanField()),
                ("has_custody_rights", models.BooleanField()),
                ("can_pickup", models.BooleanField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustodyRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                ("contact_number", models.CharField(max_length=12)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("P", "Parent"),
                            ("GP", "Grandparent"),
                            ("AV", "Aunt/Uncle"),
                            ("S", "Sibling"),
                            ("G", "Legal Guardian"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_authorized", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("verification_notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GuardianProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_number", models.CharField(max_length=12)),
                ("is_primary_contact", models.BooleanField()),
                ("created_at", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizedPickupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("P", "Parent"),
                            ("GP", "Grandparent"),
                            ("AV", "Aunt/Uncle"),
                            ("S", "Sibling"),
                            ("G", "Legal Guardian"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_authorized", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("pickup_pin", encrypted_fields.fields.EncryptedIntegerField()),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
