# Generated by Django 6.0.4 on 2026-05-18 04:54

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custodyrestriction",
            name="restriction_type",
        ),
        migrations.AddField(
            model_name="medicalnote",
            name="date_created",
            field=models.DateTimeField(
                auto_created=True,
                default=datetime.datetime(
                    2026, 5, 18, 4, 54, 54, 541478, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergies",
                to="children.child",
            ),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="severity",
            field=models.CharField(
                choices=[
                    ("M", "Mild"),
                    ("MD", "Moderate"),
                    ("S", "Severe"),
                    ("LT", "Life-Threatening"),
                    ("F", "Fatal"),
                ],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="authorizedpickupprofile",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorized_pickup",
                to="children.child",
            ),
        ),
        migrations.AlterField(
            model_name="custodyrestriction",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restrictions",
                to="children.child",
            ),
        ),
        migrations.AlterField(
            model_name="custodyrestriction",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="emergencycontact",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contact",
                to="children.child",
            ),
        ),
        migrations.AlterField(
            model_name="medicalnote",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_notes",
                to="children.child",
            ),
        ),
    ]
