# Generated by Django 6.0.4 on 2026-06-17 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
        ("enrollment", "0001_initial"),
        ("facilities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                through="enrollment.Enrollment",
                to="facilities.program",
            ),
        ),
        migrations.AddField(
            model_name="authorizedpickupprofile",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authorized_pickup",
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="allergy",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergies",
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="childguardianrelationship",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="children.child"
            ),
        ),
        migrations.AddField(
            model_name="custodyrestriction",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="restrictions",
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contact",
                to="children.child",
            ),
        ),
        migrations.AddField(
            model_name="guardianprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="childguardianrelationship",
            name="guardian",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="children.guardianprofile",
            ),
        ),
        migrations.AddField(
            model_name="medicalnote",
            name="child",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_notes",
                to="children.child",
            ),
        ),
    ]
