# Generated by Django 6.0.4 on 2026-06-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0002_remove_custodyrestriction_restriction_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicalnote",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
