# Generated by Django 6.0.4 on 2026-06-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0003_alter_medicalnote_date_created"),
        ("enrollment", "0003_alter_childschedule_days_of_week"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="children",
                through="enrollment.Enrollment",
                to="facilities.program",
            ),
        ),
    ]
