# Generated by Django 6.0.4 on 2026-05-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("children", "0001_initial"),
        ("staffing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandoffEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PU-AM", "Pickup(AM)"),
                            ("DO-AM", "Dropoff(AM)"),
                            ("PU-PM", "Pickup(PM)"),
                            ("DO-PM", "Dropoff(PM)"),
                        ],
                        max_length=5,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="staffing.staffprofile",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="children.child"
                    ),
                ),
                (
                    "pickup_person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="children.authorizedpickupprofile",
                    ),
                ),
            ],
        ),
    ]
