# Generated by Django 6.0.4 on 2026-06-17 13:40

import address.models
import django.db.models.deletion
from django.db import migrations, models

import common.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=265, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "address1",
                    address.models.AddressField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.address",
                    ),
                ),
                (
                    "address2",
                    address.models.AddressField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="address.address",
                    ),
                ),
            ],
            bases=(common.helpers.ModelModifer, models.Model),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=375)),
                ("capacity", models.IntegerField()),
                (
                    "age_group",
                    models.CharField(
                        choices=[
                            ("INF", "Infant: 0 - 18 Months"),
                            ("TOD", "Toddler: 18 Months - 3 Years"),
                            ("SA", "School Age: 3 Years to 12 Years"),
                            ("TEE", "Teenager: 13+ Years"),
                        ],
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.site",
                    ),
                ),
            ],
            bases=(common.helpers.ModelModifer, models.Model),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=375)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("PS", "Preschool"),
                            ("HD-ST", "Headstart"),
                            ("PC", "Precare"),
                            ("AS", "Afterschool"),
                        ],
                        max_length=14,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="facilities.site",
                    ),
                ),
            ],
            bases=(common.helpers.ModelModifer, models.Model),
        ),
    ]
